services:
  ct-web:
    image: nginx
    ports: 
    - "8001:80"
    - "8443:443"
    volumes:
    - "vol-web:/data"
    restart: unless-stopped


  ct-db:
    image: mariadb
    ports:
    - "3310:3306"
    volumes:
    - "vol-db:/var/lib/mysql"
    restart: unless-stopped


  ct-redis:
    image: redis
    ports:
    - "6379:6379"
    restart: unless-stopped

  ct-phpmyadmin:
    image: phpmyadmin
    ports:
    - "8080:80"
    restart: unless-stopped

name: app
volumes:
  vol-web:
  vol-db: