name: simple

services:
  app:
    image: wmustaqim1019/simple-apps
    build: .
    ports:
      -"5000:3000"
    restart: always
    volumes:
      - vol-app: /app/public/images

volumes:
  - vol-app: